apiVersion: v1
kind: Service
metadata:
  # Chart 정보 참조할때 첫글자를 대문자로
  name: "{{ .Chart.Name }}-service" 
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}   
    targetPort: {{ .Values.containerPort }}